#+begin_export html
---
layout: post
title: "收集箱"
date: 2019-03-05
categories: InBox
tags:
- InBox
---
#+end_export

日常收集和备忘，以待整理归档。

* 软件工具

** 文本编辑

*** Spacemacs 安装以及基本配置

    #+begin_src sh
      brew install ag
      brew install grep
      brew tap d12frosted/emacs-plus
      brew install emacs-plus
      # 安装完毕之后，链接我的 spacemacs 配置
      $XCFG/editor/emacs/spacemacs/linkspac.sh
      # 输入 emacs 进行初始化，如果你可以正常访问 Github 的话时间在半小时之内。
      emacs
    #+end_src

*** 删除空行
    #+begin_src text
      M-x flush-lines RET ^\s-*$ RET
    #+end_src

*** Pandoc 安装以及基本配置

    #+begin_src sh
      brew install pandoc
      # 分析器安装
      brew install pandoc-citeproc
      # 组件安装
      brew install librsvg homebrew/cask/basictex
      # 如果警告缺少字体
      tlmgr install collection-fontsrecommended
    #+end_src

** 多媒体

*** 安装视频播放器

**** iina

     #+begin_src sh
       brew cask install iina
     #+end_src

** Terminal

*** locate

    #+begin_src sh
      # mac 下更新数据库命令是
      sudo /usr/libexec/locate.updatedb
      # mac 下使用不要使用通配符，locate 自动将包含关键字的文件都检索
      locate temp
    #+end_src

*** lszrz

    - 不论是发送还是接收，，都是在服务器端输入命令执行的。
    - 无法传输大于 4G 的文件。
    - 使用 tmux 或其他多路终端屏幕可能会失败，尝试在服务器上增加 -e 选项以强制在传输过程中转义更多字符。
    - 使用 expect 或 rlogin 可能会失败，因为它期望双方之间的大多数干净的 8 位连接。

    --注：本人在 mac + zsh + iterm2 环境里使用成功，但尝试在 tmux 环境中使用未成功！--

**** 安装 lrzsz

     #+begin_src sh
       brew install lrzsz
     #+end_src

**** 下载 iTerm2 支持脚本

     #+begin_src sh
       cd /usr/local/bin
       sudo curl -O https://raw.githubusercontent.com/mmastrac/iterm2-zmodem/master/iterm2-recv-zmodem.sh
       sudo curl -O https://raw.githubusercontent.com/mmastrac/iterm2-zmodem/master/iterm2-send-zmodem.sh
       sudo chmod +x iterm2-
     #+end_src

**** 设置 iTerm2 Trigger

     在 iTerm2 的 Preferences 中，选择 `Profiles—>Default—>Advanced—>Triggers—>Edit`，设置如下 trigger

     #+end_srctext
     Regular expression: rz waiting to receive.\-\-B0100
     Action: Run Silent Coprocess
     Parameters: /usr/local/bin/iterm2-send-zmodem.sh
     Instant: checked

     Regular expression: \-\-B00000000000000
     Action: Run Silent Coprocess
     Parameters: /usr/local/bin/iterm2-recv-zmodem.sh
     Instant: checked
     #+end_src

**** 发送文件到远端服务器

     - 在远端服务器执行 `rz`
     - 本地选择文件传输
     - 等待传输指示消失

**** 接收远端服务器的文件

     - 在远端服务器执行 `sz filename1 filename2 … filenameN`
     - 本地选择目录保存
     - 等待传输指示消失

* 开发设计

** 关键字备忘

*** 字面量

在计算机科学中，字面量（literal）是用于表达源代码中一个固定值的表示法（notation）。几乎所有计算机编程语言都具有对基本值的字面量表示，诸如：整数、浮点数以及字符串；而有很多也对布尔类型和字符类型的值也支持字面量表示；还有一些甚至对枚举类型的元素以及像数组、记录和对象等复合类型的值也支持字面量表示法。

字面量是指由字母，数字等构成的字符串或者数值，它只能作为右值出现。

* 生活备忘
