#+begin_export html
---
layout: post
title: "Spacemacs MaGit 学习"
date: 2019-03-11
categories: 文本编辑
tags:
    - Spacemacs
    - Git
---
#+end_export

* 配置 Magit

Git 是一个优秀的版本控制工具，我们可以在 .spacemacs 的 ~dotspacemacs-configuration-layers~ 列表中添加 git 就可以集成 git 了。

*下面是一些常用的 git 命令，前缀为 ~SPC g~*

| Git                 | Magit                          |
|---------------------+--------------------------------|
| git init            | SPC g i                        |
| git status          | SPC g s                        |
| git add             | SPC g s 弹出层选中文件然后按 s |
| git add currentFile | SPC g S                        |
| git commit          | SPC g c c                      |
| git push            | SPC g P 按提示操作             |
| git checkout xxx    | SPC g C                        |
| git checkout -- xxx | SPC g s 弹出层选中文件然后按 u |
| git log             | SPC g l l                      |

大部分命令整合到 SPC g s 中，需要按照提示执行命令

在 commit 时，我们输入完 commit message 之后，需要按 ~C-c C-c~ 来完成 commit 操作，也可以按  ~C-c C-k~ 来取消 commit。

* MaGit 状态窗口

比 git status 显示的信息更加方便，并且也是管理窗口，可以在这里使用很多快捷命令。
只要在一个 git 目录里面，按下 ~M-m g s~ ，就会弹出 magit 状态窗口

比如下面显示有两个文件处于 staged 状态，就是可以被提交

#+begin_src text
  Staged changes (2)
  modified a.html
  modified a.org
#+end_src

* 查看 refs

按下 ~y~  键即可
可以看到 git 地址，branch 名称和 tag 名称

* git add -u 的替代方法

在正在编辑的文件上，按下 ~M-m g S~, 将当前文件变成 staged 状态。

* unstage 文件

- ~u~ 当前文件被 unstage
- ~U~ 所有文件被 unstage


* git commit 的更好的用法

反复敲命令 ~git commit -m~ 也挺累, 这里用快捷键

在前面打开的 magit status 窗口，按两下 ~c c~ ，然后会弹出新的 buffer，让输入 commit message,同时还会出现 diff 的 buffer,提示这次提交的代码做了哪些修改。

输入 message 后，然后按 ~C-c C-c~ ， 提交；
输入 message 后，然后按 ~C-c C-k~ ， 取消。


* git push 的替代方法

在 status buffer 上，按下 ~P m~ 。

* git log 的替代方法

在 status buffer 上，按下 ~l l~ 。



* git tag 管理

** 创建 tag 

 在 status buffer 上按下 ~t t~ ，然后输入 tag 名称，并指定 branch 名称，就可以在本地创建 tag 了

** push tag

 在 status buffer 上按下 ~P T~ 即可。

** 显示 tag

 仍然是 ~l l~ 。



* git diff


** 对过去的 commit 进行 diff

 选中一批，然后 ~d r~ ，就会显示差异

** 当前工作区的修改文件和仓库里面的 diff

 对某个文件修改，保存但不提交，然后用 ~d d~ 来查看修改可哪些东西。如果觉得不合适，可以用 emacs 回退操作。

* 从远程同步

git fetch 在 status buffer 上按下 ~f u~ 。
git pull 在 status buffer 上按下 ~F u~ 。

* branch 操作

** 查看本地 branch
 在 status buffer 上按下 ~y~ 。

** 切换 branch

 status buffer 上按下 ~b~ 键，进入 branch 管理界面，按下 ~b~ 就可以切换。
 创建新 branch 可以使用 ~c~ ，根据当前 branch 创建新 branch，类似于 ~checkout -b newBranch~ 。

** merge

 如果想把 develop branch 的代码合并到 master branch。应该

 1. 切换到 master branch（目标 branch)

 2. 按下 m 键，然后再按一次 m 运行 Merge Action.

 选择 develop branch (源 branch), 回车。

[[https://magit.vc/manual/magit/Diffing.html][magit diff 操作参考]]
