#+begin_export html
---
layout: post
title: "猪猪培训课"
date: 2018-08-13
categories: 培训课
tags:
    - 猪猪培训课
excerpt:
keywords: ""
---
#+end_export

* 第一课、假冒网站

为了防止女王大人被一些小黑同学、小马同学误导，第一课先聊聊假冒网站 ：）

通常对于我们这些小白同学来说，可以简单认为，大多数有名有姓的网站安全性是我们不需要考虑的，更多时候我们是被一些假冒网站给欺骗了。
所以我们先从网站地址的真实性开始。

** 搜索引擎

不要无条件的相信搜索引擎，搜索引擎关注的更多是搜索，而不是安全，真假难辨的网页，何况还有坑爹的竞价排名啊，亲。

** 链接

网页上显示的链接不见得是真实链接地址，很容易设置的啊，亲。
比如我们点击下 [[https://www.jd.com][淘宝<https://www.taobao.com/>]] 这个链接看看会去哪儿？

那我们该怎么做呢，其实很简单，把鼠标移到链接的上方，不要点击，先看看你的浏览器下方状态栏，大多数浏览器状态栏都会显示真实的链接地址。

** URL 地址

最重要的就是域名真实性，抛开域名劫持等不谈，一定要注意观察域名地址，地址里各段含义是不一样的，例如: http://user:password@www.maxthon.cn:80/mx5/ ，根据协议的不同，URL 格式会发生变化。

- ~http~ ：这是协议名称，代表 http 协议，就是我们平常的网页浏览方式；
- ~://~ ： 是协议的分隔符。
- ~user@passowrd~ ：用户名和密码，通常在网页访问中不需要。
- ~@~ ：用户名密码和域名的分隔符。
- ~www~ ：这是子域名， ~www~ 通常设置和主域名地址一致；
- ~maxthon.cn~ ：这是 *最重要的主域名* ，通常这代表网站是否真实，经常会被小马同学用相近字符假冒， ~0~ 、 ~o~ 和 ~1~ 、 ~l~ 等，比如 ~http://www.maxth0n.cn~ ；
- ~:80~ ：这是网站服务器的协议端口号，80 端口是 http 的默认端口，可以省略不写。
- ~mx5~ ：这是网站子域名下的路径，表示某个功能资源页面。末尾的 ~/~ 代表访问 ~mx5/~ 目录下的缺省文件，如果末尾没有 ~/~ 代表访问 ~mx5~ 文件，如果找不到 ~mx5~ 文件，再去寻找 ~mx5/~ 目录，所以不要省略末尾的斜杠，会导致两次查找。如果网站做得不好，容易被劫持跳转到一个假冒网站，所以就算主域名是真实的，功能页面的字符串如果太长了也要仔细看看，是否包含其他网站的域名或 ip 地址等信息，如果有，就要小心了！

先简单说到这里，亲，随时要注意哈，坑太多了，对面和你聊天的真的有可能是只猪啊 ：）
